[id]

[main]
# Caps Lock dual-function:  tap -> Esc, hold -> Ctrl
capslock = overload(control, esc)

# Esc becomes Caps Lock
esc = capslock

# Both Alt keys become Super/Meta/Windows keys
leftalt = leftmeta
rightalt = rightmeta

# Both Windows/Super keys become Alt
leftmeta = leftalt
rightmeta = rightalt

# Menu/Application key becomes Alt
compose = rightalt
end = rightalt
