general {
    lock_cmd = qs --config noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = qs --config noctalia-shell ipc call lockScreen lock
}

listener {
    timeout = 10
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 30
    on-timeout = wlr-randr --output LVDS-1 --off
    on-resume  = wlr-randr --output LVDS-1 --on
}

listener {
    timeout = 10
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
    timeout = 300
    on-timeout = qs --config noctalia-shell ipc call lockScreen lock
}

listener {
    timeout = 20
    on-timeout = qs --config noctalia-shell ipc call brightness set 0
    on-resume = qs --config noctalia-shell ipc call brightness set 50 && brightnessctl -r
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
